# Copyright (C) 2011-2020 Project SkyFire <http://www.projectskyfire.org/
# Copyright (C) 2008-2021 TrinityCore <http://www.trinitycore.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

os: linux
dist: focal
group: travis_latest
language: cpp
sudo: required

matrix:
  include:
   - name: "Ubuntu 21.04 (Hirsute Hippo) with GCC"
     env: DOCKER="ubuntu:hirsute" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.04 (Focal Fossa) with GCC"
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) with GCC"
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

git:
  depth: 1

branches:
  only:
    - main
    - trunk

before_install:
  - sudo rm -rf /var/lib/dpkg/lock
  - sudo wget https://dev.mysql.com/get/mysql-apt-config_0.8.17-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.17-1_all.deb
  - sudo apt update
  - sudo apt-get update
  - sudo apt-get install libncurses5-dev libace-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar
  - sudo apt-get install openssl libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev

install:
  - export CXX=${COMPILER_CXX}
  - export CC=${COMPILER_C}
  - ${COMPILER_CXX} --version
  - ${COMPILER_C} --version

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DSCRIPTS=1 -DTOOLS=0 -DCMAKE_BUILD_TYPE=Release

script:
  - make -j2
