# Copyright (C) 2011-2018 Project SkyFire <http://www.projectskyfire.org/
# Copyright (C) 2008-2018 TrinityCore <http://www.trinitycore.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

os: linux
dist: xenial
sudo: required
compiler: gcc
group: stable

language: cpp

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:aridev/xenial -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo rm -rf /var/lib/dpkg/lock
  - sudo apt-get install gcc-8 g++-8
  - export CXX=g++-8 CC=gcc-8
  - sudo wget https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt update
  - sudo apt-get install libncurses5-dev libace-dev
  - sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar
  - sudo apt-get install openssl libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev

  
script:
  - mkdir build
  - cd build
  - cmake ../ -DSCRIPTS=0 -DTOOLS=1
  - make -j16

notifications:
  irc:
    channels:
      - "irc.rizon.net#project_skyfire"
    on_success: always
    on_failure: always
